### ISSUE TITLE
I would like to contribute to the project

### ISSUE THREAD

**Issue by williamcosta** [peterasplund/MagentoReact#7]
Hi, my name is William, I am Frontend developer and currently working with Magento and started studying ReactJS.

With my studies I had the idea to implement ReactJS with Magento and just found this project. I would like to congratulate the involved so far by project.

I wonder if you are accepting contributions, and what the project status are developing yet.

**Comment by Poggen** [comment]
Hi William,

Sorry for the late reply — I'm currently on vacation. We are developing this as a demo / MVP for our company and, as a result, there will most certainly be parts that will be slightly opinionated towards the needs of our company. However, you are more than welcome to contribute and the project should be fully functional regardless of any opinionated parts (these should be pretty easy to strip out in your own fork if you want to create a new MagentoReact site for your employer). Give me a few days to clean up the todo issue (#1) – then, feel free to go to town!
BR,
Oscar
